### ISSUE TITLE
Edição do arquivo EVN

### ISSUE THREAD

**Issue by Cobra-Mafia** [victorsouzaleal/lbot-whatsapp#1]
Achei o arquivo **env.js** que está na pasta **lib**, editei os campos com as keys.
Editei parcialmente, não coloquei as keys para ACRCLOUD.
Quando rodo o ele não reconhece essas keys.

[ENV] ✓ Número do DONO configurado.
[ENV] A API do REMOVEBG ainda não foi configurada
[ENV] A API do NEWSAPI ainda não foi configurada
[ENV] A API do RAPIDAPI ainda não foi configurada
[ENV] A API do ACRCloud ainda não foi configurada corretamente

**Comment by victorsouzaleal** [comment]
O arquivo para edição é o .env na raiz do projeto e não o env.js.
