### ISSUE TITLE
Erro download Instagram.

### ISSUE THREAD

**Issue by HugoLibanori** [victorsouzaleal/lbot-whatsapp#14]
Toda vez que tento baixar Vídeo do Instagram da erro. Oq poderia ser?

[SERVIDOR] Servidor iniciado!
/home/ubuntu/lbot-whatsapp/node_modules/instagram-url-direct/node_mod>
  var error = new Error(message);
              ^

Error: Request failed with status code 403
    at createError (/home/ubuntu/lbot-whatsapp/node_modules/instagram>
    at settle (/home/ubuntu/lbot-whatsapp/node_modules/instagram-url->
    at IncomingMessage.handleStreamEnd (/home/ubuntu/lbot-whatsapp/no>
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_>
  config: {
    url: 'https://sssinstagram.com/pt',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false

Esse é o começo do erro que aparece, vlw.

**Comment by victorsouzaleal** [comment]
Corrigido na versão nova do https://github.com/victorsouzaleal/instagram-direct-url

Tente usar este comando dentro da pasta do bot para atualizar os todos os módulos : 
```bash
> npm update
```

ou só o modulo do Instagram em específico:
```bash
> npm i --save instagram-url-direct@latest
```
