### ISSUE TITLE
Comando !grupos do menu admin apresenta erros

### ISSUE THREAD

**Issue by Vineees** [victorsouzaleal/lbot-whatsapp#21]
![Screenshot_17](https://github.com/victorsouzaleal/lbot-whatsapp/assets/72805423/01eb5a41-5b7b-4f20-9c86-28dbe8272cbf)

**Comment by victorsouzaleal** [comment]
Opa, consegue me dizer quantos em grupos mais ou menos você estava?

**Comment by Vineees** [comment]
Atualmente em 15 grupos

**Comment by victorsouzaleal** [comment]
![image](https://github.com/victorsouzaleal/lbot-whatsapp/assets/4674786/8d1f7af3-8659-48e1-95ce-128991205be9)

Estarei fazendo mudanças no comando de grupos na próxima atualização e adicionando o novo comando linkgrupos para evitar de sempre puxar todos os links dos grupos que é a causa desse erro de 'rate-overlimit' (limite do proprio WhatsApp).

Obrigado por relatar o problema 👍
