### ISSUE TITLE
Comandos !play e !yt com erro.

### ISSUE THREAD

**Issue by HugoLibanori** [victorsouzaleal/lbot-whatsapp#27]
salve mano, mais um aviso mesmo esses comandos não estão funcionando, estão dando erro 403. eu aqui troquei pra essa @distube/ytdl-core@latest é um fork mais atualizado. resolveu o problema. vlw

**Comment by victorsouzaleal** [comment]
Valeu, foi corrigido lá no outro repositório só reiniciar o bot que deve voltar a funcionar.

**Comment by Sordinni** [comment]
As vezes **@distube/ytdl-core** dá o mesmo erro, eu achei uma solução que estou usando há 4 dias sem erros.

é só mudar
`let functionName = utils.between(body, `&&(b=a.get("n"))&&(b=`, `(b)`);`
para
`let functionName = utils.between(body, `&&(b=a.get("n"))&&(b=`, `(b)`) || utils.between(body, `&&(b=String.fromCharCode(110),c=a.get(b))&&(c=`, `(c)`);`

Na linha `58` em `\ytdl-core\lib\sig.js`
