### ISSUE TITLE
Qrquivo .env faltando

### ISSUE THREAD

**Issue by georgecolossi** [victorsouzaleal/lbot-whatsapp#28]
Faltando arquivo .env na raiz do projeto para configuração dos API KEYS

**Comment by HugoLibanori** [comment]
> Faltando arquivo .env na raiz do projeto para configuração dos API KEYS

Cara, você iniciou o Bot?, você tem que iniciar o Bot pela primeira vez pra ele criar os arquivos nescessários.

**Comment by georgecolossi** [comment]
Opa, tudo bem amigo? Iniciei o bot sim! Inclusive usei em um grupo normalmente, mesmo assim o arquivo .env não apareceu.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by victorsouzaleal** [comment]
Está usando no Windows, Linux ou Termux?
