### ISSUE TITLE
Comando !animes não está funcionando direito

### ISSUE THREAD

**Issue by Numbzin** [victorsouzaleal/lbot-whatsapp#29]
Eu baixei o bot pra estudar, pq to aprendendo js na faculdade e vi que o comando !animes não está mandando os lançamentos, analisei o código e fui no site, vi que a div estava diferente (no console log retornava 0) e alterei para o nome atual, ficando assim ->    const $animes = document.querySelectorAll('div.mainContainer.mwidth > div.epiContainer > div.ultimosAnimesHomeItem'); mas mesmo assim não funcionou.. não sei oq pode ser

**Comment by victorsouzaleal** [comment]
Opa boa noite, parece que era um problema no site que as vezes não trazia as informações corretamente (talvez alguma proteção contra DDOS)

Atualizei a api para utilizar outro site, se estiver na última versão do bot é só digitar `yarn upgrade`  antes de iniciar o bot para atualizar a api

**Comment by Numbzin** [comment]
Bom dia, obrigado por resolver bro, Tmj!!
