### ISSUE TITLE
Arquivo .ENV

### ISSUE THREAD

**Issue by HugoLibanori** [victorsouzaleal/lbot-whatsapp#3]
Olá não estou encontrando o arquivo .env na raiz, poderia me ajudar como proseguir?

**Comment by HugoLibanori** [comment]
ja achei mano tem que iniciar ele primeiro para criar o arquivos... mals.

**Comment by victorsouzaleal** [comment]
Sim, ele cria os arquivos necessários na primeira inicialização :)
