### ISSUE TITLE
Limite de 1m30 em transcrições

### ISSUE THREAD

**Issue by andreresende** [victorsouzaleal/lbot-whatsapp#30]
Este é um limite do bot ou do deepgram? Entrei na conta do deepgram e não encontrei essa informação. Se for o caso, como contornar essa limitação? Obrigado!

 erro_limite: "[❗] Houve um erro na transcrição, o áudio ultrapassa *1m30s*",

**Comment by andreresende** [comment]
Encontrei a solução: editar essa linha em utilidades.js: if(citacao.segundos > 90)
 
 De qualquer maneira, creio que fica a sugestão, 90s me parece pouco para áudios.

**Comment by victorsouzaleal** [comment]
Realmente eu não quis deixar muito longo pois o Deepgram na API gratuita tem um limite em minutos, mas posso considerar deixar como padrão 3-5 minutos. Valeu :+1:
