### ISSUE TITLE
Função para filtrar mensagens 

### ISSUE THREAD

**Issue by lucianosipriano88** [victorsouzaleal/lbot-whatsapp#32]
Primeiramente parabéns pelo projeto. Muito bem feito e documentado 

Gostaria de saber, se tem alguma função no bot em que ele permita somente um tipo de padrão de mensagem , e caso não seja igual ele apaga a mensagem automaticamente. 

Exemplo disso, eu uso ele num grupo de vendas, e precisaria que todas as mensagens tenha o mesmo padrão, com título preço descrição e etc

**Comment by victorsouzaleal** [comment]
Olá, obrigado por usar e deixar sua sugestão :) 

E não, não há esse tipo de função pois não é o propósito desse bot, o propósito sempre foi servir para entretenimento de grupos, não uso e nem recomendo o bot para fins comerciais.
