### ISSUE TITLE
problemas com conexão

### ISSUE THREAD

**Issue by brxvamp** [victorsouzaleal/lbot-whatsapp#33]
Olá, voce poderia liberar uma base do seu bot sem comandos para que eu possa analizar o porque o meu bot não consegue se conectar ao whatsappp

**Comment by HugoLibanori** [comment]
cara seria mais facil vc mandar qual o erro vc esta recebendo, assim seria mais facil de te ajudar. ta tendo erro na leitura do qrcode?

**Comment by Brenohlima** [comment]
troquei a funçao alink onde ela paga os links que as pessoas mandam em meu grupo troquei para quando alguem manda um link de grupo meu bot entra no grupo sozinho so que queria olhar com o domo se e possivel ele me falar onde eu altero as permiçoes do bot para q essa funçao seja ativada so por mim q configurei , so que essa funçao so e ativada por um adm do grupo de whatsapp

**Comment by HugoLibanori** [comment]
> troquei a funçao alink onde ela paga os links que as pessoas mandam em meu grupo troquei para quando alguem manda um link de grupo meu bot entra no grupo sozinho so que queria olhar com o dono se e possivel ele me falar onde eu altero as permiçoes do bot para q essa funçao seja ativada so por mim q configurei , so que essa funçao so e ativada por um adm do grupo de whatsapp mas queria que qualquer grupo q meu bot esteja mesmo nao sendo adm do grupo ele leia os links e entrava nos grupos sozinho

cara é só vc colocar assim
if (!mensagem_dono)
    return await socket.responderTexto(
      c,
      id_chat,
      comandos_info.outros.permissao.apenas_dono_bot,
      mensagem
    );
vc troca !usuario_admin por esse codigo no arquivo grupo.js
