### ISSUE TITLE
Problema ao bloquear contatos

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [victorsouzaleal/lbot-whatsapp#36]
![imagem_2024-10-01_134214860](https://github.com/user-attachments/assets/ce451132-7ca0-443e-8be1-181481e8ddb1)

**Comment by vitor-zanatta-walter** [comment]
![{057CE8B1-350C-4FD6-8646-933F72ABE4F1}](https://github.com/user-attachments/assets/d666afaf-2e31-4d86-be98-8dc2b00213f2)
 
Acho que o problema está na linha 190, onde ele busca pelo usuário na propria lista que está iterando.

**Comment by victorsouzaleal** [comment]
Obrigado por relatar, foi corrigido em https://github.com/victorsouzaleal/lbot-whatsapp/commit/7e31361f607024614fde673a7925e7d5a1457bb4.
