### ISSUE TITLE
Problema no comando .fotobot

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [victorsouzaleal/lbot-whatsapp#37]
pode dar uma checada no comando .fotobot? não sei dizer se o problema está nesse código ou na API do Baileys.

**Comment by victorsouzaleal** [comment]
Funcionando aqui, qual erro você está tendo e como você está usando ele?

Em ter., 22 de out. de 2024 às 01:17, vitor-zanatta-walter <
***@***.***> escreveu:

**Comment by vitor-zanatta-walter** [comment]
Ele não retorna nenhum erro no console, o comando é interompido nessa parte:
`await socket.alterarFotoPerfil(c, numero_bot, fotoBuffer)`

A partir dessa linha de codigo nada é executado e o bot não devolve nenhuma resposta.

Em casos onde eu faço um erro proposital com o comando .fotobot ele responde normalmente. 

![{9B675850-CF58-4B1E-9E3C-92232F6C2F1C}](https://github.com/user-attachments/assets/70a8b60a-5028-4ee6-a0b1-f1315ec2ce60)


Código completo do comando:
![{91B17B4F-C1AB-453B-B737-60F4B581AC1C}](https://github.com/user-attachments/assets/3a41535e-2c60-486c-aa9f-f2ca65921985)

**Comment by victorsouzaleal** [comment]
Acontece só com essa imagem em especifico ou qualquer uma?

Em ter., 22 de out. de 2024 às 19:49, vitor-zanatta-walter <
***@***.***> escreveu:

**Comment by vitor-zanatta-walter** [comment]
Eu atualizei a lib do whiskeysockets e voltou a funcionar, desculpa o incomodo.
acredito que essas ultimas atualizações do whatsapp estão abalando bastante as coisas.

**Comment by victorsouzaleal** [comment]
Sim está tendo bastante atualizações e estão começando a integrar a IA no WhatsApp Web, então coisas doidas podem acontecer kk
