### ISSUE TITLE
dúvida quanto a alteração de função

### ISSUE THREAD

**Issue by rodrasdmasdm** [victorsouzaleal/lbot-whatsapp#38]
Oii. Primeiramente, meus parabéns por este projeto.
tentei acessar a pasta e procurar o local para alterar a config para evitar que o bot envie mensagem de saudação sempre que é adicionado em algum grupo, no entanto, não consegui.
Sabe me dizer como realizo isso ?

**Comment by victorsouzaleal** [comment]
Olá, seguinte é só ir em bot/baileys/eventosSocket.js e colocar as 2 barras na linha 82 como na imagem abaixo.

![image](https://github.com/user-attachments/assets/dbbc72fa-df04-41f7-86d5-bc1a5ba1e2a7)

**Comment by rodrasdmasdm** [comment]
Muito obrigado!!!
Devo imaginar o trabalho que você teve para implementar esse projeto kkkkk Meus parabéns novamente

**Comment by rodrasdmasdm** [comment]
Aproveitando a deixa. Tem alguma função no bot que podemos desabilitá-lo em algum grupo em específico ? e deixar habilitado apenas em alguns ?

**Comment by victorsouzaleal** [comment]
> Aproveitando a deixa. Tem alguma função no bot que podemos desabilitá-lo em algum grupo em específico ? e deixar habilitado apenas em alguns ?

Não, até porque mesmo que fizesse algo pra configurar no grupo ele teria que entrar antes e dar saudações de qualquer jeito então não faz muito sentido. Então a unica opção viavel é desativar globalmente.

**Comment by rodrasdmasdm** [comment]
show demais. Mt obg
