### ISSUE TITLE
Como controlar o BOT

### ISSUE THREAD

**Issue by kaiangoncalves** [victorsouzaleal/lbot-whatsapp#4]
Bom dia! Sou novato na programação e me interessei por esse projeto. Instalei tudo certinho, no terminal tudo aparece que foi iniciado, mas o navegador não abre. Quando visualizo meu gerenciador de tarefas, as abas do chrome estão em execução, mas não abre para mim. Minha dúvida é onde utilizo os comandos para controlar o bot, como exemplo o !menu. Estou perdido quanto a isso. Agradeço desde já. Parabéns pelo projeto.

**Comment by victorsouzaleal** [comment]
Bem acho que você descobriu que o navegador roda em modo "headless" ou seja não tem uma interface visual kk
