### ISSUE TITLE
[❗] Houve um erro no comando *!ig*.  Motivo: *Erro ao obter o video, verifique o link ou tente mais tarde.*

### ISSUE THREAD

**Issue by piveta157013** [victorsouzaleal/lbot-whatsapp#41]
O comando !ig tá dando erro toda vez que coloco o comando pra baixa  através do link do Instagram da erro seja qualquer link de  fotos vídeos da esse erro

**Comment by victorsouzaleal** [comment]
Manda um link de exemplo que esteja dando erro.

**Comment by piveta157013** [comment]
Fui pega qualquer link do Instagram que tava dado erro deis de ontem pra te manda e fui testa no bot como falou que aí tava tudo normal agora aqui voltou a baixa normalmente de novo sem da aquele erro . Obrigado por me responde é ter visto isso pra mim  e parabéns pelo seu bot  que Deus te abençoe

**Comment by victorsouzaleal** [comment]
> Fui pega qualquer link do Instagram que tava dado erro deis de ontem pra te manda e fui testa no bot como falou que aí tava tudo normal agora aqui voltou a baixa normalmente de novo sem da aquele erro . Obrigado por me responde é ter visto isso pra mim e parabéns pelo seu bot que Deus te abençoe

Realmente o comando de instagram estava com um problema mas foi resolvido hoje de manhã :+1:
