### ISSUE TITLE
Download TikTok instável

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [victorsouzaleal/lbot-whatsapp#42]
O comando para baixar videos do tiktok apresenta instabilidade e funciona só algumas vezes.

O erro mais comum é esse:

![{ADFE7325-BF43-41F4-9E74-C7A45B0791A6}](https://github.com/user-attachments/assets/a4a2c68b-dce3-42e9-acb1-f8eefba7e9f0)

link de exemplo: https://vm.tiktok.com/ZMh4dvqps/

**Comment by victorsouzaleal** [comment]
Reinicia e vê se melhorou

**Comment by vitor-zanatta-walter** [comment]
Ta funcionando bem melhor agora, todos os videos que testei ele baixou.
Só não funciona com imagens, mas da pra aceitar.

**Comment by victorsouzaleal** [comment]
> Ta funcionando bem melhor agora, todos os videos que testei ele baixou. Só não funciona com imagens, mas da pra aceitar.

Manda um exemplo ai de imagem pra eu olhar, talvez dê pra corrigir.

**Comment by vitor-zanatta-walter** [comment]
![{0CA21C7E-A653-4268-AB84-0F68FAB3BC5B}](https://github.com/user-attachments/assets/e8bd3c58-ecdf-4446-b8af-bfd443269436)

link: https://vm.tiktok.com/ZMh425JsU/

**Comment by victorsouzaleal** [comment]
Hmm é possível corrigir sim, mas vou ter que fazer uma nova versão do bot para ele baixar mais de uma imagem... Eu não uso Tiktok então não sabia que tinha post com múltiplas imagens.

**Comment by victorsouzaleal** [comment]
Mas se reiniciar deve estar funcionando pelo menos o download da primeira imagem sem dar erro. :+1:

**Comment by vitor-zanatta-walter** [comment]
pra mim ele tentou mandar a imagem como video, mas pelo menos não foi um erro XD

**Comment by victorsouzaleal** [comment]
> pra mim ele tentou mandar a imagem como video, mas pelo menos não foi um erro XD

É acabei de ver aqui tentei também kkkk o comando de Tiktok não está preparado pra enviar imagens na epoca eu achava que só dava pra enviar videos...

Então espera mais um pouco que logo mais vou fazer uma alteração e lançar uma versão nova, ai aproveitando já vai baixar todas as imagens.

**Comment by vitor-zanatta-walter** [comment]
Sem pressa, eu não sei como você consegue dar conta de lidar com tantas issues que to te passando kkkkk

**Comment by vitor-zanatta-walter** [comment]
Eu tô diariamente testando os comandos e ja coloquei alguns novos também, esse bot ta muito top

**Comment by victorsouzaleal** [comment]
https://github.com/victorsouzaleal/lbot-whatsapp/commit/1aa86ffbce037e21442388c084c143ec32a1feef Só dar uma olhada ai na alteração se quiser já colocar no seu código

**Comment by vitor-zanatta-walter** [comment]
perfeito!
