### ISSUE TITLE
Bem vindo

### ISSUE THREAD

**Issue by danecool** [victorsouzaleal/lbot-whatsapp#44]
Opa, eu novamente.
Não encontrei a configuração de bem-vindo assim que uma pessoa entra no grupo.
Porém verifiquei que consta na lista de admin.
--
Desculpe se estou interrompendo ou incomodando, apenas estou listando o que vou encontrando ok. Se estiver atrapalhando me avise.
Abraaaaços

**Comment by victorsouzaleal** [comment]
Oi, !bv guia

**Comment by danecool** [comment]
SHOW! Eu ia vir aqui apagar, pois acabei de ver kkkkk 
Muito obrigado !!!
