### ISSUE TITLE
!topativos exibindo 1 a menos no loop

### ISSUE THREAD

**Issue by danecool** [victorsouzaleal/lbot-whatsapp#45]
Opa, o comando !topativos está trazendo 1 a menos do que foi solicitado.

!topativos 5 ( traz 4 )

!topativos 4 ( traz 3 )

![image](https://github.com/user-attachments/assets/385bd121-d2a6-423d-8274-9de3d15f13ee)

**Comment by victorsouzaleal** [comment]
Pronto acabei de corrigir na nova versão, valeu :+1:
