### ISSUE TITLE
Comando ( .tw ) só funciona com videos.

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [victorsouzaleal/lbot-whatsapp#46]
em testes, só consegui baixar videos por meio do comando, em imagens ocorre o segiunte erro:

![{90014FFA-C392-47D6-8C35-0B00318E0EAB}](https://github.com/user-attachments/assets/89473970-6b05-4d8e-a68f-57c8779c2f58)

link de exemplo: https://x.com/NewsLiberdade/status/1858179630663881200

**Comment by victorsouzaleal** [comment]
Dei uma olhada aqui e o problema não parece ser da imagem ou do video em si, a API as vezes retorna erro 404 aleatóriamente

**Comment by victorsouzaleal** [comment]
Reiniciem e testem agora se está melhor

**Comment by vitor-zanatta-walter** [comment]
Parece que está funcionando bem agora, obrigado!
