### ISSUE TITLE
Loop Console

### ISSUE THREAD

**Issue by maradona4** [victorsouzaleal/lbot-whatsapp#6]
√ Version: 4.7.1
√ Browser Launched
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│       (index)       │                                                                   Values                                                                    │
├─────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│     WA_VERSION      │                                                                 '2.2126.10'                                                                 │
│       PAGE_UA       │ 'WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' │
│ WA_AUTOMATE_VERSION │                                                                   '4.7.1'                                                                   │
│   BROWSER_VERSION   │                                                       'HeadlessChrome/91.0.4472.124'                                                        │
│         OS          │                                                                'Windows 10'                                                                 │
│      START_TS       │                                                                1625826184683                                                                │
└─────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
× Session data most likely expired due to manual host account logout. Please re-authenticate this session.
√ Downloaded patches in 0.133s

**Comment by victorsouzaleal** [comment]
Corrigido na ultima versão
